server:
  port: 8086
  servlet:
    context-path: /hello
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Laserjet.Sdc1
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: WARN
    org.joseph.hello: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR